### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by Mulkave** [drcz/CONSpiracy-language#1]

**Comment by drcz** [comment]
Hi Abed!

Very good question -- who knows?! (is it an issue though?)

if you mean _how to use it_, provided you have guile2.0 on your system, you need to get nice-9 module, and then just run `prototype/CONSpiracy-repl.scm`.

nice-9 (eg here: [https://github.com/drcz/random-crap/blob/master/game-of-life-tdd/nice-9.scm](https://github.com/drcz/random-crap/blob/master/game-of-life-tdd/nice-9.scm)) was written by Panicz Maciej Godek (https://github.com/panicz -- he has a _really_ weird finger), and is "deprecated" now, since Panicz Godek blessed humanity with [https://github.com/plande/grand-scheme](https://github.com/plande/grand-scheme) --  **I don't always scheme, but when I do, I prefer (grand scheme)**.

So, for example on debian-like system it should suffice to
```
apt-get install guile-2.0
wget "https://raw.githubusercontent.com/drcz/random-crap/master/game-of-life-tdd/nice-9.scm"
mv nice-9.scm /usr/share/guile/2.0/ice-9/ # or wherever your guile implementation has it's ice-9 modules
chmod +x CONSpiracy-repl.scm
./CONSpiracy-repl.scm
```
it should welcome you with a friendly
```
   (-- ALGORITHMIC LANGUAGE CONSpiracy v0.1 --)
copyleft by Scislav Dercz 2016/09/09-18, Eindhoven
type (halt) to quit

READY.
>
```
Some [shitty] introduction to the language can be found in comments of `prototype/CONSpiracy-implementation.scm` ; also, in `prototype/` you can find some example "programs" and "libraries", the most interesting one being `group-theory.cpr` which allows you to experiment with some basic notions of abstract algebra (mostly group theory).

if you do know algorithmic language scheme, you can admire some [mostly unfinished] attempts on compiling CONSpiracy to simpler languages in the other directories.
if you don't know scheme, I highly recommend giving it a try (especially with (grand scheme)).

this winter i should publish a ``better'' implementation and some introductory course, so stay tuned ;)

I resigned form some "features" the current version offers, in particular re-evaluationg definitions each time, which makes it pretty slow (but the point was to extend the idea of my previous one-night language ZJEB).

Also, mind this version surely has bugs and inconsistencies -- I wrote the prototype in a few evenings in a coffee-shop near the center of Eindhoven; therefore the language is pretty dope itself.

If I didn't answer your question feel free to re-open this one.
Cheers!
